// +build !embed

// Automagically generated by yaber v0.1 (https://github.com/lmas/yaber),
// please avoid editting this file as it might be regenerated again.

package assettemplates

import (
        "io/ioutil"
        "path/filepath"
)

func Asset(path string) ([]byte, error) {
	return ioutil.ReadFile(path)
}

func AssetDir(dir string) (map[string][]byte, error) {
        tmp, e := ioutil.ReadDir(dir)
        if e != nil {
                return nil, e
        }

        files := make(map[string][]byte)
        for _, f := range tmp {
                name := filepath.Join(dir, f.Name())
                body, e := ioutil.ReadFile(name)
                if e != nil {
                        return nil, e
                }
                files[name] = body
        }
        return files, nil
}
